# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses : actions/setup-node@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        node-version: '12'

    - run : npm install

    - run : npm run build
    
    - run : npm run test

    - run : node dist/release.js --platform=win
  
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses : actions/setup-node@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        node-version: '12'

    - run : npm install

    - run : npm run build
    
    - run : npm run test

    - run : node dist/release.js --platform=linux


